version: "3"
services:
    web:
        image: web-image
        hostname: web
        container_name: "web"
        command: "bash entrypoint.sh"
        volumes: 
            - cmsdata:/data
        depends_on:
            - db
        environment:
            - ALLOW_OVERRIDE=true
        networks:
            - obvius
        ports:
            - "10080:80"
            - "10443:443"
    
    db:
        image: db-image
        hostname: db
        restart:
           unless-stopped
        container_name: "db"
        networks:
            - obvius
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=ku
            - MYSQL_PASSWORD=kudbpassword
            - MYSQL_DATABASE=ku
        ports:
            - "3307:3306"
    
    solr:
        image: solr
        hostname: solr
        container_name: "solr"
        #restart:
                #    unless-stopped
        networks:
            - obvius
        volumes:
            - ./solr/obvius-conf:/opt/solr/server/solr/configsets/obvius
        entrypoint:
            - docker-entrypoint.sh
            - solr-precreate
            - obvius
            - /opt/solr/server/solr/configsets/obvius
        ports:
            - "18983:8983"

    cron:
        image: cron-image
        hostname: cron
        container_name: "cron"
        depends_on:
            - db
        networks:
            - obvius
        volumes:
            - "cmsdata:/data"
        ports:
            - "5544:5544"

networks: 
    obvius:

volumes:
    cmsdata:
