version: "3"
services:
    web:
        image: apache-test
        hostname: web
        container_name: "web"
        command: "apachectl -D FOREGROUND"
        volumes: 
            - ./web/volumes/www.ku.dk:/var/www/www.ku.dk
            - ./web/volumes/obvius:/var/www/obvius
            - ./web/volumes/tinymce3:/var/www/tinymce3
        depends_on:
            - db
        environment:
            - ALLOW_OVERRIDE=true
        networks:
            - obvius
        ports:
            - "80:80"
            - "443:443"
    db:
        image: maria-git
        restart:
           unless-stopped
        #volumes:
           #- ./etc/mysql/my.cnf:/etc/mysql/my.cnf
        container_name: "db"
        networks:
            - obvius
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=ku
            - MYSQL_PASSWORD=kudbpassword
            - MYSQL_DATABASE=ku
        ports:
            - "3307:3306"
networks: 
    obvius:
