version: "3"
services:
    web:
        image: web-image
        hostname: web
        container_name: "web"
        command: "bash entrypoint.sh"
        volumes: 
            - cmsdata:/data
        environment:
            - ALLOW_OVERRIDE=true
        networks:
            - obvius
        ports:
            - "10081:80"
            - "10444:443"
        links:
            - db-slim:db

    web-dev:
        image: web-image
        hostname: web-dev
        container_name: "web-dev"
        command: "bash entrypoint.sh"
        volumes:
            - cmsdata:/data
            - ku_code:/var/www/www.ku.dk
            - obvius_code:/var/www/obvius
        environment:
            - ALLOW_OVERRIDE=true
        networks:
            - obvius
        ports:
            - "10080:80"
            - "10443:443"
        links:
            - db-seeded:db

    db-slim:
        image: db-image
        hostname: db-slim
        restart:
           unless-stopped
        container_name: "db-slim"
        networks:
            - obvius
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=ku
            - MYSQL_PASSWORD=kudbpassword
            - MYSQL_DATABASE=ku
        ports:
            - "3307:3306"

    db-seeded:
        image: db-image
        hostname: db-seeded
        restart:
           unless-stopped
#        volumes:
#           - "/var/lib/mysql_bak:/var/lib/mysql"
        container_name: "db-seeded"
        networks:
            - obvius
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=ku
            - MYSQL_PASSWORD=kudbpassword
            - MYSQL_DATABASE=ku
        ports:
            - "3308:3306"
    
    solr:
        image: solr
        hostname: solr
        container_name: "solr"
        #restart:
                #    unless-stopped
        networks:
            - obvius
        volumes:
            - ./solr/obvius-conf:/opt/solr/server/solr/configsets/obvius
        entrypoint:
            - docker-entrypoint.sh
            - solr-precreate
            - obvius
            - /opt/solr/server/solr/configsets/obvius
        ports:
            - "18983:8983"

    cron:
        image: cron-image
        hostname: cron
        container_name: "cron"
        networks:
            - obvius
        volumes:
            - "cmsdata:/data"
        ports:
            - "5544:5544"

networks: 
    obvius:

volumes:
    cmsdata:
    ku_code:
        driver: local
        driver_opts:
            device: /var/www/www.ku.dk
            o: bind
    obvius_code:
        driver: local
        driver_opts:
            device: /var/www/obvius
            o: bind
