version: "3"
services:
    #The obvius image must be used briefly as a service for it to be built as Docker Compose does not support task-style services that do not run on 'docker-compose up'
    obvius:
        build: ./obvius
        image: obvius
        hostname: obvius
        container_name: "obvius"
        restart: "no"
    web:
        #Image inherits from obvius image
        build: ./web
        image: web-obvius
        hostname: web
        container_name: "web"
        command: "bash entrypoint.sh"
        volumes: 
            - cmsdata:/var/www/www.ku.dk/data
            - logs:/var/www/www.ku.dk/logs
            - uploaddata:/var/www/www.ku.dk/docs/upload
        environment:
            - ALLOW_OVERRIDE=true
        ports:
            - "10080:80"
            - "10443:443"
        depends_on:
          - obvius #Need to ensure obvius image is built first when running docker-compose up --build
    db:
        build: ./db
        image: db
        hostname: db
        restart:
           unless-stopped
        container_name: "db"
        #command: "bash entrypoint.sh"
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_USER=ku
            - MYSQL_PASSWORD=kudbpassword
            - MYSQL_DATABASE=ku
        ports:
            - "3307:3306"
    solr:
        image: solr
        hostname: solr
        container_name: "solr"
        volumes:
            - ./solr/obvius-conf:/opt/solr/server/solr/configsets/obvius
        entrypoint:
            - docker-entrypoint.sh
            - solr-precreate
            - obvius
            - /opt/solr/server/solr/configsets/obvius
        ports:
            - "18983:8983"
    always-cron:
        build: ./cron
        image: cron
        hostname: always-cron
        container_name: "always-cron"
        command: "cron && tail -f /var/log/cron.log"
        restart: always
        volumes:
            - "cmsdata:/data"
        ports:
            - "5544:5544"
        depends_on:
          - obvius #Need to ensure obvius image is built first when running docker-compose up --build
networks:
    obvius:
volumes:
    cmsdata:
    uploaddata:
    logs:
    #Adjust according to local code path!
    ku_code:
        driver: local
        driver_opts:
            device: /var/www/www.ku.dk
#            device: ${PWD}/obvius/src/www.ku.dk
            o: bind
    obvius_code:
        driver: local
        driver_opts:
            device: /var/www/obvius
 #           device: ${PWD}/obvius/src/obvius
            o: bind
